### ISSUE TITLE
Server: ERD

### ISSUE THREAD

**Issue by developerasun** [asunlabs/courses#13]
## Sub-tasks

- [x] Should finish:  [Entity Relationship Diagram (ERD) Tutorial - Part 1](https://youtu.be/QpdhBUYk7Kk)
- [x] Should finish:  [Entity Relationship Diagram (ERD) Tutorial - Part 2](https://youtu.be/-CuY5ADwn24)
- [x] Should finish:  [Database Tutorial for Beginners](https://youtu.be/wR0jg0eQsZA)
